[build]
builder = "dockerfile"
dockerfile = "./Dockerfile"

[deploy]
startCommand = "node index.js"
restartPolicyMaxRetries = 5
healthcheckPath = "/api/health"
healthcheckInterval = 30

[env]
PORT = "3001"
NODE_ENV = "production"
